using '../main.bicep'

param environmentName = 'sandbox'
param location = 'eastus2'
param postgresLocation = 'eastus2'
param resourceGroupName = 'rg-dpi-sandbox'
param namePrefix = 'dpi'
param postgresAdminLogin = 'dpiadmin'
param postgresAdminPassword = 'change-me-at-deploy-time'
param keyVaultAdminPrincipalId = ''
